#NOMBRE DEL PIPELINE
name: CI DevOps Practica
#EL ON SIGNIFICA QUE SE VA A EJECUTAR AUTOMATICAMENTE CADA VEZ QUE SE HAGA PUSH
on:
  push:
#SE VA A EJECUTAR TODO LO DE LA RAMA MAIN
    branches: ["main"]
#TRABAJOS QUE SE VAN A REALIZAR
jobs:
  build: #COMPILAR
    runs-on: ubuntu-latest #SISTEMA OPERATIVO DONDE SE COMPILA
  
    steps:
    
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test
    
